import { Asset, Author } from './types';

export const initialAuthors: Author[] = [
  {
    id: 'guest',
    name: 'GuestUser',
    avatarGradient: 'linear-gradient(135deg, #4A7C59, #82b892)',
    bio: 'Welcome to AssetShelf! This is a demo guest account. Start uploading your 3D assets and libraries to share with the community.',
    joinedDate: '2024-01-15',
  },
  {
    id: 'author1',
    name: 'PolyMaster',
    avatarGradient: 'linear-gradient(135deg, #667eea, #764ba2)',
    bio: '3D artist specializing in low-poly game assets. 10+ years of experience in game development. Creating assets for indie devs and modding communities.',
    joinedDate: '2023-03-22',
  },
  {
    id: 'author2',
    name: 'NeonForge',
    avatarGradient: 'linear-gradient(135deg, #f093fb, #f5576c)',
    bio: 'Sci-fi and cyberpunk 3D modeler. Building the future, one polygon at a time. All assets optimized for real-time rendering.',
    joinedDate: '2023-06-10',
  },
  {
    id: 'author3',
    name: 'CodeCraft',
    avatarGradient: 'linear-gradient(135deg, #4facfe, #00f2fe)',
    bio: 'Full-stack developer creating tools and libraries for 3D web experiences. Open source advocate.',
    joinedDate: '2023-01-05',
  },
  {
    id: 'author4',
    name: 'TextureWiz',
    avatarGradient: 'linear-gradient(135deg, #fa709a, #fee140)',
    bio: 'Texture artist and material designer. Specializing in PBR workflows and procedural generation.',
    joinedDate: '2023-08-18',
  },
  {
    id: 'author5',
    name: 'MoCapStudio',
    avatarGradient: 'linear-gradient(135deg, #a18cd1, #fbc2eb)',
    bio: 'Motion capture studio providing high-quality character animations for games and VR experiences.',
    joinedDate: '2023-05-30',
  },
];

export const initialAssets: Asset[] = [
  {
    id: 'asset1',
    title: 'Medieval Castle Kit',
    description: 'A comprehensive modular castle building kit with over 50 unique pieces. Includes walls, towers, gates, bridges, and decorative elements. All pieces snap together seamlessly for easy level design. Optimized for real-time rendering with LOD support. Perfect for RPG games, strategy titles, or medieval-themed mods.\n\nFeatures:\n• 50+ modular pieces\n• PBR materials (4K textures)\n• LOD support (3 levels)\n• Unity & Unreal compatible\n• Collision meshes included',
    authorId: 'author1',
    thumbnailGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 40%, #0f3460 100%)',
    screenshots: [
      'linear-gradient(135deg, #1a1a2e, #16213e, #0f3460)',
      'linear-gradient(135deg, #0f3460, #1a1a2e, #16213e)',
      'linear-gradient(160deg, #16213e, #0f3460, #1a1a2e)',
      'linear-gradient(200deg, #0f3460, #16213e, #1a1a2e)',
    ],
    files: [
      { name: 'MedievalCastleKit_v2.1.zip', size: '245 MB', type: 'zip' },
      { name: 'Textures_4K.zip', size: '180 MB', type: 'zip' },
      { name: 'Documentation.pdf', size: '2.4 MB', type: 'pdf' },
      { name: 'UnityPackage.unitypackage', size: '210 MB', type: 'unity' },
    ],
    tags: ['medieval', 'castle', 'modular', 'fantasy', 'rpg', 'game-ready', 'pbr'],
    category: 'model',
    rating: 247,
    userVote: 0,
    views: 3420,
    downloads: 891,
    createdAt: '2024-06-15',
  },
  {
    id: 'asset2',
    title: 'Sci-Fi Weapon Pack',
    description: 'A collection of 25 futuristic weapons ranging from pistols to heavy artillery. Each weapon features detailed geometry, PBR materials, and rigged components for animation. Suitable for FPS games, sci-fi RPGs, and space-themed projects.\n\nIncludes:\n• 8 Pistols & Sidearms\n• 6 Rifles & Carbines\n• 5 Heavy Weapons\n• 4 Melee Weapons\n• 2 Special/Experimental Weapons',
    authorId: 'author2',
    thumbnailGradient: 'linear-gradient(135deg, #0c0c1d 0%, #1a0a2e 40%, #2d1b69 100%)',
    screenshots: [
      'linear-gradient(135deg, #0c0c1d, #1a0a2e, #2d1b69)',
      'linear-gradient(135deg, #2d1b69, #0c0c1d, #1a0a2e)',
      'linear-gradient(160deg, #1a0a2e, #2d1b69, #0c0c1d)',
    ],
    files: [
      { name: 'SciFi_Weapons_v1.3.fbx', size: '156 MB', type: 'fbx' },
      { name: 'Textures_PBR.zip', size: '320 MB', type: 'zip' },
      { name: 'Blender_Source.blend', size: '89 MB', type: 'blend' },
    ],
    tags: ['sci-fi', 'weapons', 'high-poly', 'pbr', 'rigged', 'game-ready'],
    category: 'model',
    rating: 189,
    userVote: 0,
    views: 2815,
    downloads: 634,
    createdAt: '2024-05-20',
  },
  {
    id: 'asset3',
    title: 'React Three Fiber Utilities',
    description: 'A comprehensive utility library for React Three Fiber projects. Provides hooks, components, and helpers for common 3D web development tasks. Includes camera controllers, post-processing effects, physics integration helpers, and performance optimization tools.\n\nKey Features:\n• Custom hooks for common patterns\n• Pre-built camera controllers\n• Post-processing effect components\n• Physics helper utilities\n• Performance monitoring tools\n• TypeScript support',
    authorId: 'author3',
    thumbnailGradient: 'linear-gradient(135deg, #0a192f 0%, #112240 40%, #1d3557 100%)',
    screenshots: [
      'linear-gradient(135deg, #0a192f, #112240, #1d3557)',
      'linear-gradient(135deg, #1d3557, #0a192f, #112240)',
      'linear-gradient(160deg, #112240, #1d3557, #0a192f)',
    ],
    files: [
      { name: 'r3f-utils-2.0.0.tgz', size: '45 KB', type: 'tgz' },
      { name: 'README.md', size: '12 KB', type: 'md' },
    ],
    tags: ['react', 'three.js', 'open-source', 'library'],
    category: 'library',
    rating: 312,
    userVote: 0,
    views: 5200,
    downloads: 2340,
    createdAt: '2024-04-10',
    githubUrl: 'https://github.com/example/r3f-utils',
  },
  {
    id: 'asset4',
    title: 'Low-Poly Nature Bundle',
    description: 'Beautiful low-poly nature assets including trees, rocks, flowers, grass, and terrain pieces. Over 120 individual assets perfect for stylized games. Lightweight and mobile-friendly.\n\nContents:\n• 40 Trees & Bushes\n• 25 Rock Formations\n• 20 Flowers & Plants\n• 15 Grass Patches\n• 10 Terrain Tiles\n• 10 Water Elements',
    authorId: 'author1',
    thumbnailGradient: 'linear-gradient(135deg, #1a472a 0%, #2d6a4f 40%, #40916c 100%)',
    screenshots: [
      'linear-gradient(135deg, #1a472a, #2d6a4f, #40916c)',
      'linear-gradient(135deg, #40916c, #1a472a, #2d6a4f)',
      'linear-gradient(160deg, #2d6a4f, #40916c, #1a472a)',
      'linear-gradient(200deg, #40916c, #2d6a4f, #1a472a)',
    ],
    files: [
      { name: 'LowPolyNature_v3.0.zip', size: '78 MB', type: 'zip' },
      { name: 'Unity_Package.unitypackage', size: '72 MB', type: 'unity' },
      { name: 'Godot_Import.zip', size: '65 MB', type: 'zip' },
    ],
    tags: ['low-poly', 'environment', 'stylized', 'game-ready', 'modular', 'unity', 'godot'],
    category: 'model',
    rating: 178,
    userVote: 0,
    views: 2100,
    downloads: 567,
    createdAt: '2024-07-02',
  },
  {
    id: 'asset5',
    title: 'PBR Material Library',
    description: 'A collection of 100+ PBR materials ready for use in any 3D application. Includes metals, fabrics, wood, stone, concrete, and more. All materials are seamless and tileable at 4K resolution.\n\nEach material includes:\n• Albedo / Base Color\n• Normal Map\n• Roughness Map\n• Metallic Map\n• Ambient Occlusion\n• Height / Displacement Map',
    authorId: 'author4',
    thumbnailGradient: 'linear-gradient(135deg, #3d1c02 0%, #8b4513 40%, #cd853f 100%)',
    screenshots: [
      'linear-gradient(135deg, #3d1c02, #8b4513, #cd853f)',
      'linear-gradient(135deg, #cd853f, #3d1c02, #8b4513)',
      'linear-gradient(160deg, #8b4513, #cd853f, #3d1c02)',
    ],
    files: [
      { name: 'PBR_Materials_4K.zip', size: '2.1 GB', type: 'zip' },
      { name: 'PBR_Materials_2K.zip', size: '890 MB', type: 'zip' },
      { name: 'Preview_Sheet.png', size: '15 MB', type: 'png' },
    ],
    tags: ['pbr', 'realistic', 'textures', 'blender', 'unity', 'unreal'],
    category: 'texture',
    rating: 156,
    userVote: 0,
    views: 1890,
    downloads: 445,
    createdAt: '2024-03-28',
  },
  {
    id: 'asset6',
    title: 'Character Animation Set',
    description: 'Professional motion-captured character animations suitable for humanoid characters. Includes locomotion, combat, interaction, and idle animations. Compatible with standard humanoid rigs.\n\nAnimation Categories:\n• Locomotion (walk, run, sprint, crouch)\n• Combat (sword, bow, magic, dodge)\n• Interaction (pickup, push, pull, climb)\n• Idle (breathing, looking around, fidget)\n• Emotes (wave, dance, sit, sleep)',
    authorId: 'author5',
    thumbnailGradient: 'linear-gradient(135deg, #2c003e 0%, #512b58 40%, #7b2d8e 100%)',
    screenshots: [
      'linear-gradient(135deg, #2c003e, #512b58, #7b2d8e)',
      'linear-gradient(135deg, #7b2d8e, #2c003e, #512b58)',
      'linear-gradient(160deg, #512b58, #7b2d8e, #2c003e)',
    ],
    files: [
      { name: 'CharacterAnims_v2.fbx', size: '340 MB', type: 'fbx' },
      { name: 'AnimList_Reference.pdf', size: '1.2 MB', type: 'pdf' },
      { name: 'Mixamo_Compatible.zip', size: '290 MB', type: 'zip' },
    ],
    tags: ['animated', 'characters', 'rigged', 'game-ready', 'unity', 'unreal'],
    category: 'animation',
    rating: 203,
    userVote: 0,
    views: 2950,
    downloads: 712,
    createdAt: '2024-02-14',
  },
  {
    id: 'asset7',
    title: 'Modular Dungeon Kit',
    description: 'A dark, atmospheric dungeon tileset with modular pieces for building underground levels. Includes corridors, rooms, stairs, traps, and decorative props. Features baked lighting for quick setup.\n\nPieces include:\n• Corridor segments (straight, corner, T-junction, cross)\n• Room templates (small, medium, large)\n• Vertical connections (stairs, ladders, shafts)\n• Props (torches, barrels, chains, bones)\n• Trap mechanisms',
    authorId: 'guest',
    thumbnailGradient: 'linear-gradient(135deg, #1b1b2f 0%, #162447 40%, #1f4068 100%)',
    screenshots: [
      'linear-gradient(135deg, #1b1b2f, #162447, #1f4068)',
      'linear-gradient(135deg, #1f4068, #1b1b2f, #162447)',
      'linear-gradient(160deg, #162447, #1f4068, #1b1b2f)',
    ],
    files: [
      { name: 'DungeonKit_v1.0.zip', size: '132 MB', type: 'zip' },
      { name: 'Textures.zip', size: '95 MB', type: 'zip' },
    ],
    tags: ['medieval', 'modular', 'fantasy', 'rpg', 'environment', 'game-ready'],
    category: 'model',
    rating: 45,
    userVote: 0,
    views: 620,
    downloads: 89,
    createdAt: '2024-08-01',
  },
  {
    id: 'asset8',
    title: 'Unity Shader Collection',
    description: 'A curated collection of custom shaders for Unity URP and HDRP. Includes toon shading, dissolve effects, force fields, holographic displays, and more. Each shader comes with a custom inspector and documentation.\n\nShader Types:\n• Toon / Cell Shading\n• Dissolve & Disintegration\n• Force Fields & Shields\n• Holographic & Glitch\n• Water & Liquid\n• Snow & Ice Accumulation',
    authorId: 'author3',
    thumbnailGradient: 'linear-gradient(135deg, #0d1b2a 0%, #1b2838 40%, #2a3f54 100%)',
    screenshots: [
      'linear-gradient(135deg, #0d1b2a, #1b2838, #2a3f54)',
      'linear-gradient(135deg, #2a3f54, #0d1b2a, #1b2838)',
      'linear-gradient(160deg, #1b2838, #2a3f54, #0d1b2a)',
    ],
    files: [
      { name: 'ShaderCollection_URP.unitypackage', size: '28 MB', type: 'unity' },
      { name: 'ShaderCollection_HDRP.unitypackage', size: '32 MB', type: 'unity' },
      { name: 'ShaderGraph_Sources.zip', size: '18 MB', type: 'zip' },
    ],
    tags: ['unity', 'open-source', 'tool'],
    category: 'tool',
    rating: 267,
    userVote: 0,
    views: 4100,
    downloads: 1890,
    createdAt: '2024-01-20',
    githubUrl: 'https://github.com/example/unity-shaders',
  },
  {
    id: 'asset9',
    title: 'Cyberpunk City Props',
    description: 'Neon-lit cyberpunk city props and environmental assets. Features holographic signs, futuristic vending machines, street furniture, and atmospheric elements. Emissive materials included for that authentic cyberpunk glow.\n\n60+ unique props organized by type:\n• Street Furniture (benches, poles, barriers)\n• Signage (neon signs, holo-ads, displays)\n• Machines (vending, ATMs, terminals)\n• Vehicles (parked cars, bikes, drones)\n• Atmosphere (steam vents, trash, cables)',
    authorId: 'author2',
    thumbnailGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a0033 40%, #330066 100%)',
    screenshots: [
      'linear-gradient(135deg, #0a0a1a, #1a0033, #330066)',
      'linear-gradient(135deg, #330066, #0a0a1a, #1a0033)',
      'linear-gradient(160deg, #1a0033, #330066, #0a0a1a)',
    ],
    files: [
      { name: 'CyberpunkProps_v2.zip', size: '410 MB', type: 'zip' },
      { name: 'Emissive_Textures.zip', size: '180 MB', type: 'zip' },
    ],
    tags: ['sci-fi', 'cyberpunk', 'props', 'environment', 'high-poly', 'pbr'],
    category: 'model',
    rating: 134,
    userVote: 0,
    views: 1560,
    downloads: 312,
    createdAt: '2024-07-18',
  },
  {
    id: 'asset10',
    title: 'Three.js Scene Manager',
    description: 'A lightweight scene management library for Three.js applications. Handles scene transitions, asset loading, and state management with a clean API. Supports both vanilla Three.js and React Three Fiber.\n\nCapabilities:\n• Scene transition effects (fade, wipe, dissolve)\n• Async asset loading with progress tracking\n• Scene state serialization\n• Hot module replacement support\n• Plugin architecture for extensions',
    authorId: 'guest',
    thumbnailGradient: 'linear-gradient(135deg, #0b132b 0%, #1c2541 40%, #3a506b 100%)',
    screenshots: [
      'linear-gradient(135deg, #0b132b, #1c2541, #3a506b)',
      'linear-gradient(135deg, #3a506b, #0b132b, #1c2541)',
    ],
    files: [
      { name: 'scene-manager-1.2.0.tgz', size: '32 KB', type: 'tgz' },
      { name: 'examples.zip', size: '1.5 MB', type: 'zip' },
    ],
    tags: ['three.js', 'library', 'open-source', 'react'],
    category: 'library',
    rating: 28,
    userVote: 0,
    views: 340,
    downloads: 78,
    createdAt: '2024-09-05',
    githubUrl: 'https://github.com/example/scene-manager',
  },
  {
    id: 'asset11',
    title: 'Vehicle Model Pack',
    description: 'A diverse collection of 15 vehicle models ranging from sedans to trucks. Each vehicle is game-ready with optimized geometry, PBR textures, and separated parts for customization.\n\nVehicle Types:\n• 4 Sedans\n• 3 SUVs\n• 2 Sports Cars\n• 2 Trucks\n• 2 Motorcycles\n• 1 Bus\n• 1 Emergency Vehicle',
    authorId: 'author1',
    thumbnailGradient: 'linear-gradient(135deg, #1a1a1a 0%, #333333 40%, #4d4d4d 100%)',
    screenshots: [
      'linear-gradient(135deg, #1a1a1a, #333333, #4d4d4d)',
      'linear-gradient(135deg, #4d4d4d, #1a1a1a, #333333)',
      'linear-gradient(160deg, #333333, #4d4d4d, #1a1a1a)',
    ],
    files: [
      { name: 'VehiclePack_FBX.zip', size: '290 MB', type: 'zip' },
      { name: 'VehiclePack_OBJ.zip', size: '310 MB', type: 'zip' },
      { name: 'Textures_2K.zip', size: '150 MB', type: 'zip' },
    ],
    tags: ['vehicles', 'modern', 'game-ready', 'pbr', 'low-poly'],
    category: 'model',
    rating: 95,
    userVote: 0,
    views: 1200,
    downloads: 234,
    createdAt: '2024-04-25',
  },
  {
    id: 'asset12',
    title: 'Procedural Texture Generator',
    description: 'A node-based procedural texture generation tool that runs in the browser. Create seamless PBR texture sets with a visual editor. Export to PNG, EXR, or directly to your 3D application.\n\nNode Types:\n• Noise generators (Perlin, Worley, Simplex)\n• Pattern generators (bricks, tiles, weave)\n• Color operations (blend, adjust, gradient)\n• Filter operations (blur, sharpen, warp)\n• Output nodes (albedo, normal, roughness, etc.)',
    authorId: 'author4',
    thumbnailGradient: 'linear-gradient(135deg, #2b0f04 0%, #5c2018 40%, #8c3a2b 100%)',
    screenshots: [
      'linear-gradient(135deg, #2b0f04, #5c2018, #8c3a2b)',
      'linear-gradient(135deg, #8c3a2b, #2b0f04, #5c2018)',
      'linear-gradient(160deg, #5c2018, #8c3a2b, #2b0f04)',
    ],
    files: [
      { name: 'ProceduralTexGen_v3.zip', size: '12 MB', type: 'zip' },
      { name: 'NodePresets.json', size: '450 KB', type: 'json' },
    ],
    tags: ['textures', 'tool', 'open-source', 'blender'],
    category: 'tool',
    rating: 178,
    userVote: 0,
    views: 2300,
    downloads: 890,
    createdAt: '2024-05-12',
    githubUrl: 'https://github.com/example/proc-texgen',
  },
];
